export const FETCH_WALKS_START = 'FETCH_WALKS_START';
export const FETCH_WALKS_SUCCESS = 'FETCH_WALKS_SUCCESS';
export const FETCH_WALKS_ERROR = 'FETCH_WALKS_ERROR';

export const SHOW_WALK_START = 'SHOW_WALK_START';
export const SHOW_WALK_SUCCESS = 'SHOW_WALK_SUCCESS';
export const SHOW_WALK_ERROR = 'SHOW_WALK_ERROR';

export const CREATE_WALK_START = 'CREATE_WALK_START';
export const CREATE_WALK_SUCCESS = 'CREATE_WALK_SUCCESS';
export const CREATE_WALK_ERROR = 'CREATE_WALK_ERROR';

export const UPDATE_WALK_START = 'UPDATE_WALK_START';
export const UPDATE_WALK_SUCCESS = 'UPDATE_WALK_SUCCESS';
export const UPDATE_WALK_ERROR = 'UPDATE_WALK_ERROR';

export const DELETE_WALK_START = 'DELETE_WALK_START';
export const DELETE_WALK_SUCCESS = 'DELETE_WALK_SUCCESS';
export const DELETE_WALK_ERROR = 'DELETE_WALK_ERROR';
